PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX prov:	<http://www.w3.org/ns/prov#>

CONSTRUCT { ?spreadsheet a prov:Entity ;
          dcterms:description ?desc ;
          prov:atTime ?date}
WHERE {
  BIND (<%URI%> as ?editor)
  ?activity prov:used ?spreadsheet ;
  		prov:atTime ?date .
        {?spreadsheet dcterms:creator ?editor }
        UNION {?spreadsheet dcterms:contributor ?editor}
  ?spreadsheet dcterms:description ?desc
} ORDER BY ASC(?date)