PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX dcmitype: <http://purl.org/dc/dcmitype/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX nm: <http://nomisma.org/id/>
PREFIX nmo: <http://nomisma.org/ontology#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?uri ?type ?label ?role ?roleLabel ?begin ?end WHERE {
  ?uri org:hasMembership ?membership ;
       skos:prefLabel ?label FILTER (langMatches(lang(?label), "en")) .
  ?uri rdf:type ?type FILTER (?type != skos:Concept)
  ?membership org:organization nm:%ID% .
  OPTIONAL {?membership org:role ?role . 
           ?role skos:prefLabel ?roleLabel FILTER (langMatches(lang(?roleLabel), "en"))}
  OPTIONAL {?membership nmo:hasStartDate ?begin }
  OPTIONAL {?membership nmo:hasEndDate ?end }
} ORDER BY ?begin ?label